<a href="https://colab.research.google.com/github/omercengiz/PythonCourse/blob/master/silinecek.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
pd.Series([10, -5, 1.1, 77.7])

0    10.0
1    -5.0
2     1.1
3    77.7
dtype: float64

In [ ]:
pd.Series([10, -5, 1.1, 77.7], index=["Chandler", "Bing", "Bender", "Rodriguez"])

Chandler     10.0
Bing         -5.0
Bender        1.1
Rodriguez    77.7
dtype: float64

In [ ]:
data = {
    "isim": ["Ahmet", "Ezgi", "Mehmet", "Sevda"],
    "boy": [180, 170, 150, np.nan],
    "ayakkabi_no": [42, np.nan, 39, 36],
    "kilo": [80, 50, 70, 45]
}

In [ ]:
print(data)

{'isim': ['Ahmet', 'Ezgi', 'Mehmet', 'Sevda'], 'boy': [180, 170, 150, nan], 'ayakkabi_no': [42, nan, 39, 36], 'kilo': [80, 50, 70, 45]}


In [ ]:
from pprint import pprint
pprint(data)

{'ayakkabi_no': [42, nan, 39, 36],
 'boy': [180, 170, 150, nan],
 'isim': ['Ahmet', 'Ezgi', 'Mehmet', 'Sevda'],
 'kilo': [80, 50, 70, 45]}


In [ ]:
rand_numbers = np.random.random((7, 4))
rand_numbers

array([[0.95943803, 0.77338016, 0.33261452, 0.25955663],
       [0.72265078, 0.05205603, 0.40165607, 0.65656963],
       [0.31884868, 0.42420329, 0.05159324, 0.01666683],
       [0.50492224, 0.85183682, 0.24628161, 0.90302348],
       [0.03103594, 0.36289873, 0.76872714, 0.41371931],
       [0.27527   , 0.92445293, 0.73464982, 0.87516319],
       [0.93154097, 0.04140702, 0.90543912, 0.0581104 ]])

In [ ]:
# Data structure also contains labeled axes (rows and columns).
# Etiketlenmiş eksenler içeren veri tipi ( satırlar ve sütunlar ).
df = pd.DataFrame(rand_numbers)
df

0         1         2         3
0  0.959438  0.773380  0.332615  0.259557
1  0.722651  0.052056  0.401656  0.656570
2  0.318849  0.424203  0.051593  0.016667
3  0.504922  0.851837  0.246282  0.903023
4  0.031036  0.362899  0.768727  0.413719
5  0.275270  0.924453  0.734650  0.875163
6  0.931541  0.041407  0.905439  0.058110

In [ ]:
df = pd.DataFrame(rand_numbers, columns=["00.00", "06.00", "12.00", "18.00"])
df

00.00     06.00     12.00     18.00
0  0.959438  0.773380  0.332615  0.259557
1  0.722651  0.052056  0.401656  0.656570
2  0.318849  0.424203  0.051593  0.016667
3  0.504922  0.851837  0.246282  0.903023
4  0.031036  0.362899  0.768727  0.413719
5  0.275270  0.924453  0.734650  0.875163
6  0.931541  0.041407  0.905439  0.058110

In [ ]:
dates = pd.date_range("20210309", periods=7)
dates

DatetimeIndex(['2021-03-09', '2021-03-10', '2021-03-11', '2021-03-12',
               '2021-03-13', '2021-03-14', '2021-03-15'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
df = pd.DataFrame(rand_numbers,
                  index=dates,
                  columns=["00.00", "06.00", "12.00", "18.00"])
df

00.00     06.00     12.00     18.00
2021-03-09  0.959438  0.773380  0.332615  0.259557
2021-03-10  0.722651  0.052056  0.401656  0.656570
2021-03-11  0.318849  0.424203  0.051593  0.016667
2021-03-12  0.504922  0.851837  0.246282  0.903023
2021-03-13  0.031036  0.362899  0.768727  0.413719
2021-03-14  0.275270  0.924453  0.734650  0.875163
2021-03-15  0.931541  0.041407  0.905439  0.058110

In [ ]:
df.dtypes

00.00    float64
06.00    float64
12.00    float64
18.00    float64
dtype: object

In [ ]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20210309"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "validation", "train"]),
        "F": "foo",
    }
)
df2

A          B    C  D           E    F
0  1.0 2021-03-09  1.0  3        test  foo
1  1.0 2021-03-09  1.0  3       train  foo
2  1.0 2021-03-09  1.0  3  validation  foo
3  1.0 2021-03-09  1.0  3       train  foo

In [ ]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [ ]:
df.head()

00.00     06.00     12.00     18.00
2021-03-09  0.959438  0.773380  0.332615  0.259557
2021-03-10  0.722651  0.052056  0.401656  0.656570
2021-03-11  0.318849  0.424203  0.051593  0.016667
2021-03-12  0.504922  0.851837  0.246282  0.903023
2021-03-13  0.031036  0.362899  0.768727  0.413719

In [ ]:
df.head(2)

00.00     06.00     12.00     18.00
2021-03-09  0.959438  0.773380  0.332615  0.259557
2021-03-10  0.722651  0.052056  0.401656  0.656570

In [ ]:
df.tail()

00.00     06.00     12.00     18.00
2021-03-11  0.318849  0.424203  0.051593  0.016667
2021-03-12  0.504922  0.851837  0.246282  0.903023
2021-03-13  0.031036  0.362899  0.768727  0.413719
2021-03-14  0.275270  0.924453  0.734650  0.875163
2021-03-15  0.931541  0.041407  0.905439  0.058110

In [ ]:
df.tail(2)

00.00     06.00     12.00     18.00
2021-03-14  0.275270  0.924453  0.734650  0.875163
2021-03-15  0.931541  0.041407  0.905439  0.058110

In [ ]:
df.index

DatetimeIndex(['2021-03-09', '2021-03-10', '2021-03-11', '2021-03-12',
               '2021-03-13', '2021-03-14', '2021-03-15'],
              dtype='datetime64[ns]', freq=None)

In [ ]:
df.columns

In [ ]:
df.to_numpy()

array([[0.95943803, 0.77338016, 0.33261452, 0.25955663],
       [0.72265078, 0.05205603, 0.40165607, 0.65656963],
       [0.31884868, 0.42420329, 0.05159324, 0.01666683],
       [0.50492224, 0.85183682, 0.24628161, 0.90302348],
       [0.03103594, 0.36289873, 0.76872714, 0.41371931],
       [0.27527   , 0.92445293, 0.73464982, 0.87516319],
       [0.93154097, 0.04140702, 0.90543912, 0.0581104 ]])

In [ ]:
df.describe()

00.00     06.00     12.00     18.00
count  7.000000  7.000000  7.000000  7.000000
mean   0.534815  0.490034  0.491566  0.454687
std    0.351585  0.368215  0.314719  0.366845
min    0.031036  0.041407  0.051593  0.016667
25%    0.297059  0.207477  0.289448  0.158834
50%    0.504922  0.424203  0.401656  0.413719
75%    0.827096  0.812608  0.751688  0.765866
max    0.959438  0.924453  0.905439  0.903023

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
df

00.00     06.00     12.00     18.00
2021-03-09  0.959438  0.773380  0.332615  0.259557
2021-03-10  0.722651  0.052056  0.401656  0.656570
2021-03-11  0.318849  0.424203  0.051593  0.016667
2021-03-12  0.504922  0.851837  0.246282  0.903023
2021-03-13  0.031036  0.362899  0.768727  0.413719
2021-03-14  0.275270  0.924453  0.734650  0.875163
2021-03-15  0.931541  0.041407  0.905439  0.058110

In [ ]:
df.sort_index(axis=0, ascending=True)

00.00     06.00     12.00     18.00
2021-03-09  0.959438  0.773380  0.332615  0.259557
2021-03-10  0.722651  0.052056  0.401656  0.656570
2021-03-11  0.318849  0.424203  0.051593  0.016667
2021-03-12  0.504922  0.851837  0.246282  0.903023
2021-03-13  0.031036  0.362899  0.768727  0.413719
2021-03-14  0.275270  0.924453  0.734650  0.875163
2021-03-15  0.931541  0.041407  0.905439  0.058110

In [ ]:
df.sort_index(axis=1, ascending=False)

18.00     12.00     06.00     00.00
2021-03-09  0.259557  0.332615  0.773380  0.959438
2021-03-10  0.656570  0.401656  0.052056  0.722651
2021-03-11  0.016667  0.051593  0.424203  0.318849
2021-03-12  0.903023  0.246282  0.851837  0.504922
2021-03-13  0.413719  0.768727  0.362899  0.031036
2021-03-14  0.875163  0.734650  0.924453  0.275270
2021-03-15  0.058110  0.905439  0.041407  0.931541

In [ ]:
df.sort_values(by="06.00")

00.00     06.00     12.00     18.00
2021-03-15  0.931541  0.041407  0.905439  0.058110
2021-03-10  0.722651  0.052056  0.401656  0.656570
2021-03-13  0.031036  0.362899  0.768727  0.413719
2021-03-11  0.318849  0.424203  0.051593  0.016667
2021-03-09  0.959438  0.773380  0.332615  0.259557
2021-03-12  0.504922  0.851837  0.246282  0.903023
2021-03-14  0.275270  0.924453  0.734650  0.875163

In [ ]:
df["06.00"]

2021-03-09    0.773380
2021-03-10    0.052056
2021-03-11    0.424203
2021-03-12    0.851837
2021-03-13    0.362899
2021-03-14    0.924453
2021-03-15    0.041407
Freq: D, Name: 06.00, dtype: float64

In [ ]:
df[0: 3]

00.00     06.00     12.00     18.00
2021-03-09  0.959438  0.773380  0.332615  0.259557
2021-03-10  0.722651  0.052056  0.401656  0.656570
2021-03-11  0.318849  0.424203  0.051593  0.016667

In [ ]:
df[0,:]

TypeError: ignored

In [ ]:
dates[0]

Timestamp('2021-03-09 00:00:00', freq='D')

In [ ]:
df.loc[dates[0]]

00.00    0.959438
06.00    0.773380
12.00    0.332615
18.00    0.259557
Name: 2021-03-09 00:00:00, dtype: float64

In [ ]:
df.loc["20210312": "20210314", ["00.00", "18.00"]]

00.00     18.00
2021-03-12  0.504922  0.903023
2021-03-13  0.031036  0.413719
2021-03-14  0.275270  0.875163

In [ ]:
import time
print(time.time())

1615309144.8133476


In [ ]:
start = time.time()
print("Değer:", df.loc["2021-03-14", "00.00"])
print(time.time()-start)

Değer: 0.275270004659245
0.001325368881225586


In [ ]:
start = time.time()
print("Değer:", df.at["2021-03-14", "00.00"])
print(time.time()-start)

Değer: 0.275270004659245
0.002955913543701172


In [ ]:
df.iloc[0:4, 0:2]

00.00     06.00
2021-03-09  0.959438  0.773380
2021-03-10  0.722651  0.052056
2021-03-11  0.318849  0.424203
2021-03-12  0.504922  0.851837

In [ ]:
df.iloc[[0, 2, 4], [2, 3]]

12.00     18.00
2021-03-09  0.332615  0.259557
2021-03-11  0.051593  0.016667
2021-03-13  0.768727  0.413719

In [ ]:
df[df["12.00"] > 0.5]

00.00     06.00     12.00     18.00
2021-03-13  0.031036  0.362899  0.768727  0.413719
2021-03-14  0.275270  0.924453  0.734650  0.875163
2021-03-15  0.931541  0.041407  0.905439  0.058110

In [ ]:
df2 = df

In [ ]:
print(df2.iloc[0, 0])
df2.iloc[0, 0] = "HAHA"

In [ ]:
df2

In [ ]:
df

In [ ]:
df.loc["2021-03-13": "2021-03-14", "06.00": "12.00"] = np.nan
df

In [ ]:
df.dropna(how="any")

In [ ]:
df

In [ ]:
df.dropna(how="all", axis=1)

In [ ]:
df.fillna(value=0)

In [ ]:
df

In [ ]:
df.isna()

In [ ]:
df.mean()

In [ ]:
df.mean(axis=1)

In [ ]:
df.apply(lambda x: x.max())

In [ ]:
df.apply(lambda x: x.sum(), axis=1)

In [ ]:
df

In [ ]:
df.apply(np.cumsum)

In [ ]:
df3 = pd.DataFrame([
                    [1, 2, 3],
                    [4, 5, 6]
])
df3

In [ ]:
pieces = [df3[:1], df3, df3[2:]]

In [ ]:
pd.concat(pieces)

In [ ]:
first = pd.DataFrame({"key": ["value1", "value2"], "left-val": [1, 2]})
second = pd.DataFrame({"key": ["value1", "value2"], "right-val": [3, 4]})
print(first)
print("#"*20)
print(second)

In [ ]:
pd.merge(first, second, on="key")

In [ ]:
df

In [ ]:
df4 = pd.DataFrame(data)
df4

In [ ]:
data = {
    "isim": ["Ahmet", "Ezgi", "Mehmet", "Sevda", "Ezgi"],
    "boy": [180, 170, 150, 160, 150],
    "ayakkabi_no": [42, 37, 39, 36, 38],
    "kilo": [80, 50, 70, 50, 60]
}
df4 = pd.DataFrame(data)

In [ ]:
df4.groupby("kilo").mean()

In [ ]:
df4.groupby(["boy", "kilo"]).mean()